# Generated by Django 4.0.6 on 2022-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
