# Generated by Django 4.0.6 on 2022-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0003_activity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/image')),
                ('gender', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=10)),
            ],
        ),
    ]
