# Generated by Django 4.0.6 on 2022-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='java',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='python',
            field=models.BooleanField(default=False),
        ),
    ]
