# Generated by Django 4.0.6 on 2022-08-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0005_remove_student_skills_student_java_student_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='student',
            name='java',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='other',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='python',
            field=models.BooleanField(),
        ),
    ]
