# Generated by Django 4.0.6 on 2022-08-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0006_alter_student_image_alter_student_java_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
