# Generated by Django 4.0.6 on 2022-08-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rena', '0008_submitform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitForm',
        ),
    ]
